idf_component_register(
    SRCS
        "app_uart.c"
        "app_settings.c"
        "production_unlock.c"
        "esp_efuse_custom_table.c"
        "audio_player.c"
        "media_catalog.c"
        "flash_media.c"
        "gbk_font.c"
        "mp3_decoder_wrapper.cpp"
        "sd_browser.c"
        "image_viewer.c"
        "main.c"
        "audio.c"
        "avi.c"
        "mjpeg.c"
        "video_player.c"
        "raw_player.c"
        "flash_player.c"
    # "testimage_data.c"
    INCLUDE_DIRS "." "include"
    EMBED_FILES "canon.pcm"
    REQUIRES BSP esp_timer spi_flash esp_adc esp_mm efuse mbedtls bootloader_support fatfs vfs nvs_flash esp_driver_usb_serial_jtag)
