# ============================================================
# 生成内嵌 GBK16 汉字点阵头文件 main/gbk_embedded_font.h
# 用于 boot_gate 启动提示 (无 TF 卡时也显示中文):
#   "请插入SD卡" → 请,插,入,卡 + ASCII "SD"
#   "请解密"     → 请,解,密
# 每个汉字 16x16 = 32 字节, 用 System.Drawing(SimSun) 渲染。
# ============================================================
param([string]$Output = "main/gbk_embedded_font.h")

Add-Type -AssemblyName System.Drawing

$gbk = [System.Text.Encoding]::GetEncoding(936)
$font = New-Object System.Drawing.Font("SimSun", 16,
        [System.Drawing.FontStyle]::Regular,
        [System.Drawing.GraphicsUnit]::Pixel)
$bmp = New-Object System.Drawing.Bitmap(16,16,[System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit

function Get-GlyphRows([string]$ch) {
    $g.Clear([System.Drawing.Color]::White)
    $g.DrawString($ch, $font, [System.Drawing.Brushes]::Black, 0, 0)
    $rows = @()
    for ($r=0; $r -lt 16; $r++) {
        $b0=0; $b1=0
        for ($c=0; $c -lt 8; $c++) { $p=$bmp.GetPixel($c,$r); if ($p.R -lt 128) { $b0 = $b0 -bor (0x80 -shr $c) } }
        for ($c=0; $c -lt 8; $c++) { $p=$bmp.GetPixel($c+8,$r); if ($p.R -lt 128) { $b1 = $b1 -bor (0x80 -shr $c) } }
        $rows += ("        0x{0:X2}, 0x{1:X2}," -f $b0,$b1)
    }
    $codeBytes = $gbk.GetBytes($ch)
    return @{ glyphs=$rows; code=("0x{0:X2}, 0x{1:X2}" -f $codeBytes[0], $codeBytes[1]) }
}

# 需要内嵌的汉字 (用 Unicode 码点转义, 避免脚本源码编码问题):
#   请 U+8BF7, 插 U+63D2, 入 U+5165, 卡 U+5361, 解 U+89E3, 密 U+5BC6
$charlist = @(0x8BF7, 0x63D2, 0x5165, 0x5361, 0x89E3, 0x5BC6)
$chars = @($charlist | ForEach-Object { [char]$_ })
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("/* AUTO-GENERATED by tools/generate_embedded_font.ps1 — do not edit by hand */")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <stdint.h>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("/* 内嵌 GBK16 汉字点阵 (16x16, 每字 32 字节), 用于 boot_gate 启动提示 */")
[void]$sb.AppendLine("typedef struct {")
[void]$sb.AppendLine("    uint8_t gbk[2];   /* GBK 编码 (高字节在前) */")
[void]$sb.AppendLine("    uint8_t mat[32];  /* 16x16 点阵 */")
[void]$sb.AppendLine("} gbk_embedded_char_t;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("static const gbk_embedded_char_t gbk_embedded_font[] = {")
foreach ($ch in $chars) {
    $gd = Get-GlyphRows "$ch"
    [void]$sb.AppendLine("    { /* $ch GBK($($gd.code)) */")
    [void]$sb.AppendLine("      { $($gd.code) },")
    [void]$sb.AppendLine("      {")
    $gd.glyphs | ForEach-Object { [void]$sb.AppendLine($_) }
    [void]$sb.AppendLine("      },")
    [void]$sb.AppendLine("    },")
}
[void]$sb.AppendLine("};")
[void]$sb.AppendLine("#define GBK_EMBEDDED_FONT_COUNT ((int)(sizeof(gbk_embedded_font)/sizeof(gbk_embedded_font[0])))")

$path = Join-Path (Split-Path $PSScriptRoot -Parent) $Output
[System.IO.Directory]::CreateDirectory((Split-Path $path -Parent)) | Out-Null
[System.IO.File]::WriteAllText($path, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "已生成: $path ($(($chars).Count) 汉字)"
$g.Dispose(); $bmp.Dispose(); $font.Dispose()
